# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaincontent', '0002_auto_20170616_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[(b'list', b'list'), (b'News', b'News'), (b'content_list', b'content_list'), (b'gallery', b'gallery'), (b'video', b'video'), (b'pdf', b'pdf')], max_length=20, null=True),
        ),
    ]
