# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaincontent', '0003_auto_20170616_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_number',
            field=models.IntegerField(default=100),
        ),
    ]
