# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaincontent', '0004_category_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='order_number',
            field=models.IntegerField(default=100),
        ),
    ]
