# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaincontent', '0006_category_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('list', 'list'), ('News', 'News'), ('content_list', 'content_list'), ('gallery', 'gallery'), ('video', 'video')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.CharField(blank=True, choices=[('list', 'list'), ('News', 'News'), ('content_list', 'content_list'), ('gallery', 'gallery'), ('video', 'video')], max_length=20, null=True),
        ),
    ]
