# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaincontent', '0007_auto_20180128_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='emp_id',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('list', 'list'), ('News', 'News'), ('content_list', 'content_list'), ('gallery', 'gallery'), ('video', 'video'), ('pdf', 'pdf')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='emp_id',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='emp_id',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.CharField(blank=True, choices=[('list', 'list'), ('News', 'News'), ('content_list', 'content_list'), ('gallery', 'gallery'), ('video', 'video'), ('pdf', 'pdf')], max_length=20, null=True),
        ),
    ]
