# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaincontent', '0008_auto_20180610_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_number',
            field=models.IntegerField(default=100),
        ),
    ]
